<h3 class="menu-toggle>Menu</h3>
                    <br/>
                <div class="menu" >   
                    <ul>
                        <li><a href="#">Home </a></li>
                        <li><a href="#" onclick="$('#submenu1').toggle(1000);">About </a></li>
						<div id="submenu1" style="display:none;">
                            <a href="week1.html" class="sub" target="_blank">Introduction</a>                           
                        </div>
                        <li><a href="outline.html">Course Outlines</a></li>
						
                        <!--Lessons SubMenu -->
                        <li><a href="#" onclick="$('#submenu2').toggle(1300);">Lectures</a></li>
                        <div id="submenu2" style="display:none;">
                            <a href="week1.html" class="sub" target="_blank">Week1</a>
                            <a href="week2.html" class="sub" target="_blank">Week2</a>
                            <a href="week3.shtml" class="sub" target="_blank">Week3</a>
                            <a href="week4.html" class="sub" target="_blank">Week4</a>
                            <a href="week5.html" class="sub" target="_blank">Week5</a>
							<a href="week6.html" class="sub" target="_blank">Week6</a>
							<a href="week7.html" class="sub" target="_blank">Week7</a>
							<a href="week8.html" class="sub" target="_blank">Week8</a>
							<a href="week9.html" class="sub" target="_blank">Week9</a>
							<a href="week10.html" class="sub" target="_blank">Week10</a>
							<a href="week11.html" class="sub" target="_blank">Week11</a>
                        </div>
                        <!-- -->
                    </ul>
				</div>	