<ul>
                        <li><a href='index.shtml'>Home</a></li>
                        <li><a href="#" onclick="$('#submenu1').toggle(800);">About </a>
                            <ul id="submenu1" style="display:none;">
                                <li><a href='about.shtml'>About</a></li>
                                <li><a href='outline.shtml'>Outline</a></li>
                                <li><a href='studentpages.shtml'>Student Pages</a></li>
                                <li><a href='project.shtml'>Project</a></li>
                                <li><a href='answers.shtml'>Project Answers</a></li>
                                <li><a href='projectsite.shtml'>Project Site</a></li>
                                <li><a href='rationale.shtml'>Project Rationale</a></li>
                                <li><a href='intro.shtml'>Team Go for Media</a></li>                          
                            </ul>
                        </li>
                        <!--Lessons SubMenu -->
                        <li><a href="#" onclick="$('#submenu2').toggle(800);">Lectures</a>

                            <ul id="submenu2" style="display:none;">
                                <a href="week1.shtml" class="sub">Week1</a>
                                <a href="week2.shtml" class="sub">Week2</a>
                                <a href="week3.shtml" class="sub">Week3</a>
                                <a href="week4.shtml" class="sub">Week4</a>
                                <a href="week5.shtml" class="sub">Week5</a>
                                <a href="week6.shtml" class="sub">Week6</a>
                                <a href="week7.shtml" class="sub">Week7</a>
                                <a href="week8.shtml" class="sub">Week8</a>
                                <a href="week9.shtml" class="sub">Week9</a>
                                <a href="week10.shtml" class="sub">Week10</a>
                            </ul>
                        </li>
                        
                        <li><a href='contact.php'>Contact</a></li>
                        <li><a href='http://goformedia.tumblr.com/'>Blog</a></li>

                    </ul>
               
